/* Cloud 3.2. Local demo only: no real users, API calls, grades or uploads. */
const U32={groupKey:'',lastDay:'',lastMinute:'',generation:null,receipt:null,used:new Set(),receipts:[],studio:{kind:'pdf',design:'academic',subject:'micro',task:'',title:''}};
const GROUPS32={university:['ЭК-21','ЭК-22','МН-21','МН-22'],college:['СПО-21','СПО-22','СПО-31']};
const TEACHERS32={
 sokolova:{name:'Елена Викторовна Соколова',initials:'ЕС',rating:4.8,votes:24,note:'Объясняет через экономические кейсы. В ответе важны логика и аргументы.'},
 krylov:{name:'Андрей Павлович Крылов',initials:'АК',rating:4.6,votes:18,note:'Ценит последовательное решение и проверку результата. Полезно повторять примеры.'},
 lebedeva:{name:'Марина Олеговна Лебедева',initials:'МЛ',rating:4.9,votes:21,note:'Много разговорной практики. На занятиях помогают короткие подготовленные ответы.'},
 orlov:{name:'Дмитрий Игоревич Орлов',initials:'ДО',rating:4.7,votes:16,note:'Структурирует материал по темам. На семинаре важны понятные выводы.'},
 ivanova:{name:'Анна Павловна Иванова',initials:'АИ',rating:4.8,votes:19,note:'Подробно разбирает типовые задачи. Рекомендуется показывать все этапы решения.'},
 belova:{name:'Ольга Сергеевна Белова',initials:'ОБ',rating:4.6,votes:14,note:'Акцент на практических заданиях и аккуратной работе с терминологией.'}
};
const TEACHING32={
 'university:ЭК-21':['sokolova','krylov','lebedeva','sokolova'],
 'university:ЭК-22':['orlov','ivanova','belova','orlov'],
 'university:МН-21':['orlov','krylov','belova','sokolova'],
 'university:МН-22':['sokolova','ivanova','lebedeva','orlov'],
 'college:СПО-21':['orlov','ivanova','belova','orlov'],
 'college:СПО-22':['sokolova','krylov','lebedeva','sokolova'],
 'college:СПО-31':['orlov','krylov','belova','sokolova']
};
function groupKey32(){return (S.profile.education||'university')+':'+(S.profile.group||'')}
function teaching32(){return TEACHING32[groupKey32()]||null}
function teachersFor32(sid){const ix=subjects.findIndex(s=>s.id===sid),ids=teaching32();return ix>=0&&ids?[{id:ids[ix],...TEACHERS32[ids[ix]]}]:[]}
function syncGroup32(){const k=groupKey32();if(k===U32.groupKey)return;U32.groupKey=k;U32.receipt=null;S.uploadValid=false;subjects.forEach(s=>{const t=teachersFor32(s.id)[0];s.teacher=t?.name||'Преподаватель пока не определён';s.initials=t?.initials||'—'});if(teaching32())works.forEach(w=>{if(!w.ownerGroup)w.ownerGroup=k})}
function clock32(now=new Date()){
 const f=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Samara',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
 const v=Object.fromEntries(f.formatToParts(now).map(p=>[p.type,p.value]));
 const iso=`${v.year}-${v.month}-${v.day}`,date=new Date(iso+'T12:00:00Z');
 return {iso,date,year:+v.year,month:+v.month,day:+v.day,weekday:(date.getUTCDay()+6)%7,minute:+v.hour*60+(+v.minute)};
}
function iso32(d){return d.toISOString().slice(0,10)}
function addDays32(iso,n){const d=new Date(iso+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return iso32(d)}
function weekDates32(){const c=clock32(),monday=addDays32(c.iso,-c.weekday+S.week*7);return days.map((_,i)=>addDays32(monday,i))}
function minutes32(v){const [h,m]=v.split(':').map(Number);return h*60+m}
function syncClock32(){const c=clock32();if(U32.lastDay!==c.iso){U32.lastDay=c.iso;S.day=c.weekday;S.week=0;if(S.attendancePeriod!=='custom'){S.attendanceFrom=c.iso.slice(0,7)+'-01';S.attendanceTo=c.iso}}return c}
attendanceRange=function(){const c=clock32(),monday=addDays32(c.iso,-c.weekday),monthEnd=iso32(new Date(Date.UTC(c.year,c.month,0,12)));return {week:[monday,addDays32(monday,6)],month:[c.iso.slice(0,7)+'-01',monthEnd],semester:[`${c.year}-${c.month>=9?'09':'01'}-01`,`${c.year}-${c.month>=9?'12-31':'08-31'}`]}[S.attendancePeriod]||[S.attendanceFrom,S.attendanceTo]};
attendanceRecords=function(){const c=clock32(),n=new Date(Date.UTC(c.year,c.month,0)).getUTCDate(),records=[];for(let d=1;d<=n;d++){const date=`${c.year}-${String(c.month).padStart(2,'0')}-${String(d).padStart(2,'0')}`,day=(new Date(date+'T12:00:00Z').getUTCDay()+6)%7;weekData[day].forEach((v,i)=>{const future=date>c.iso||(date===c.iso&&minutes32(v[1])>c.minute);records.push({id:`a-${date}-${i}`,date,day,time:v[0],end:v[1],subject:v[2],kind:v[3],status:future?'unknown':(d+i)%8===0?'absent':(d+i)%17===0?'unknown':'present'})})}return records};
const attPage32=renderers.attendance;
renderers.attendance=()=>attPage32().replace('Демо · сентябрь 2026','Демо · '+new Intl.DateTimeFormat('ru',{month:'long',year:'numeric',timeZone:'Europe/Samara'}).format(new Date())).replace('В макете отметки заданы только до 17 сентября. Остальные показаны как «Нет отметки».','Отметки вымышлены. В примере заполнен текущий месяц; будущие пары не имеют отметок.').replaceAll('min="2026-09-01" max="2026-12-31"','');
function summary32(){const c=clock32(),rs=attendanceRecords().filter(r=>r.date<c.iso||(r.date===c.iso&&minutes32(r.end)<=c.minute)),present=rs.filter(r=>r.status==='present').length,absent=rs.filter(r=>r.status==='absent').length,unknown=rs.length-present-absent;return {present,absent,unknown,known:present+absent,rate:present+absent?Math.round(present/(present+absent)*100):null}}
function attendanceCard32(){const a=summary32();return `<article class="card u32-attendance"><div class="card-head"><h3>Общая посещаемость</h3>${icon('checkcircle')}</div><div class="c31-progress-ring" style="--progress:${a.rate??0}%"><strong>${a.rate===null?'—':a.rate+'%'}</strong></div><p class="u32-att-sub">${a.present} из ${a.known} занятий с отметкой · максимум 100%</p><div class="u32-att-legend"><span><b>${a.present}</b> посещено</span><span><b>${a.absent}</b> пропущено</span></div><p class="tiny mt-sm">Все предметы · текущий месяц · демо. Без отметки: ${a.unknown}. Такие пары не считаются пропусками.</p>${go('Посмотреть посещаемость','attendance','soft wide mt')}</article>`}
function event32(e,i,date){const s=subjects.find(s=>s.id===e[2]),c=clock32(),today=date===c.iso,current=today&&c.minute>=minutes32(e[0])&&c.minute<minutes32(e[1]),done=date<c.iso||(today&&c.minute>=minutes32(e[1])),next=today&&weekData[c.weekday].find(v=>minutes32(v[0])>c.minute)===e;return `<button class="event-row" data-action="u32-lesson" data-date="${date}" data-day="${(new Date(date+'T12:00:00Z').getUTCDay()+6)%7}" data-event="${i}"><time>${e[0]}<small>${e[1]}</small></time><span class="event-block ${current||next?'next':''}" style="--event-color:var(--${s.color})"><span class="row between wrap"><b>${s.name}</b>${current?badge('Идёт сейчас','green'):next?badge('Следующая','blue'):done?badge('Завершена','blue'):''}</span><span class="event-meta">${e[3]} · аудитория ${s.room}</span><span class="event-meta">${esc(s.teacher)}</span></span></button>`}
function todayCard32(){const c=clock32(),names=['Твой понедельник','Твой вторник','Твоя среда','Твой четверг','Твоя пятница','Твоя суббота','Твоё воскресенье'],list=weekData[c.weekday];return `<article class="card" id="u32-today"><div class="card-head"><h3>${names[c.weekday]}</h3>${link('Неделя','schedule')}</div><div class="day-summary"><span>${shortDate(c.iso)}</span><b>${list.length} пар</b></div>${list.length?list.map((e,i)=>event32(e,i,c.iso)).join(''):'<div class="empty-state"><h3>Сегодня без пар</h3><p>Так выглядит свободный день в демо-расписании.</p></div>'}<p class="tiny mt-sm">Текущая дата · время Самары. Занятия — примеры, не сведения БРСО.</p></article>`}
const home32=renderers.home;
renderers.home=()=>{const d=document.createElement('div');d.innerHTML=home32();const c=clock32();for(const h of d.querySelectorAll('.card-head h3')){if(h.textContent==='Твой четверг')h.closest('article').outerHTML=todayCard32();if(h.textContent==='Ближе к своей цели')h.closest('article').outerHTML=attendanceCard32()}const stat=[...d.querySelectorAll('.stat-card')].find(el=>el.textContent.includes('пары в четверг'));if(stat){stat.querySelector('strong').textContent=weekData[c.weekday].length;stat.querySelector('p').textContent='пар сегодня'}const gs=[...d.querySelectorAll('.stat-card')].find(el=>el.textContent.includes('группа-пример'));if(gs){gs.querySelector('strong').textContent=S.profile.group||'—';gs.querySelector('p').textContent='твоя демо-группа'}return d.innerHTML};
renderers.schedule=function(){const dates=weekDates32(),ev=weekData[S.day],current=dates[S.day];return head('Расписание','Сегодняшние пары, вся неделя и посещаемость.')+scheduleTabs('schedule')+fresh()+`<div class="schedule-grid mt"><article class="card schedule-card"><div class="week-header"><div><span class="kicker">${new Intl.DateTimeFormat('ru',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(current+'T12:00:00Z'))}</span><h2>${shortDate(dates[0])} — ${shortDate(dates[6])}</h2></div><div class="week-nav">${button(icon('back'),'u32-week','data-delta="-1" aria-label="Предыдущая неделя"','sm')}${button(icon('chevron'),'u32-week','data-delta="1" aria-label="Следующая неделя"','sm')}</div></div><div class="row between wrap mb"><span class="small">${esc(S.profile.group||'Группа не выбрана')} · демо</span><div class="segment">${['day','week'].map(v=>button(v==='day'?'День':'Неделя','schedule-view',`data-view="${v}" aria-pressed="${S.scheduleView===v}"`,S.scheduleView===v?'active':'')).join('')}</div></div><div class="week-ribbon">${dates.map((date,i)=>`<button class="day-button ${S.day===i?'current':''}" data-action="day" data-day="${i}" aria-pressed="${S.day===i}"><span>${days[i]}</span><strong>${+date.slice(-2)}</strong><i>${weekData[i].length?'•'.repeat(weekData[i].length):'—'}</i></button>`).join('')}</div>${S.scheduleView==='day'?`<div class="day-summary"><b>${shortDate(current)}</b><span>${ev.length} занятий</span></div>${ev.map((e,i)=>event32(e,i,current)).join('')||'<div class="empty-state"><h3>В примере занятий нет</h3><p>В рабочем кабинете это проверяется по расписанию твоей группы.</p></div>'}`:`<div class="u32-week-view">${dates.map((date,day)=>`<section><h3>${days[day]} · ${shortDate(date)}</h3>${weekData[day].map((e,i)=>event32(e,i,date)).join('')||'<p class="small">Без пар в примере</p>'}</section>`).join('')}</div>`}</article><aside class="stack"><article class="card"><span class="spark-icon">${icon('calendar')}</span><h3 class="mt">Текущая неделя</h3><p class="small mt-sm">Дата обновляется по времени Самары, в том числе при возвращении во вкладку.</p>${button('Вернуться к сегодня','u32-today','','soft wide mt')}</article><article class="note"><b>Демонстрационные занятия</b><p class="small mt-sm">Сетка повторяется для проверки интерфейса. В продукте расписание и преподаватели приходят из профиля БРСО, а не генерируются.</p></article></aside></div>`};
renderers.teachers=function(){const ids=teaching32(),unique=ids?[...new Set(ids)]:[];return head('Твои преподаватели','По предметам и группе '+esc(S.profile.group||'—'))+`<div class="u32-context-line">${badge(S.profile.education==='college'?'СПО':'Университет','blue')}${badge(S.profile.group||'Группа не выбрана','violet')}${button('Сменить демо-группу','u32-group','','sm')}</div><div class="note mt mb">Все имена, оценки и характеристики здесь вымышлены. В продукте преподаватели берутся из БРСО твоей группы; оценки и редакционные заметки имеют отдельный источник.</div><div class="grid g3 stagger">${unique.map(id=>{const t=TEACHERS32[id],ss=subjects.filter(s=>teachersFor32(s.id)[0]?.id===id);return `<article class="card u32-teacher"><div class="row between"><span class="avatar lg">${t.initials}</span><span class="u32-rating">${icon('star')}<b>${t.rating.toFixed(1)}</b><small>/ 5</small></span></div><h2>${t.name}</h2><div class="u32-subject-tags">${ss.map(s=>`<span>${s.name}</span>`).join('')}</div><p>${t.note}</p><div class="u32-rating-foot">${t.votes} оценок · демонстрационные значения</div></article>`}).join('')||'<article class="card"><h3>Сначала выбери группу</h3><p>Без подтверждённой группы список преподавателей не подставляется наугад.</p></article>'}</div>`};
renderers.teacher=()=>renderers.teachers();
function groupDialog32(){modal('Учебный профиль · демо',`<form id="u32-group-form"><label class="field"><span>Уровень образования</span><select id="u32-education"><option value="university" ${S.profile.education!=='college'?'selected':''}>Университет</option><option value="college" ${S.profile.education==='college'?'selected':''}>СПО</option></select></label><label class="field"><span>Группа</span><select id="u32-group-select"></select></label><div class="note">Смена группы изменит демонстрационный состав преподавателей. Реальные учебные данные не запрашиваются. Подтверждение загрузки будет отменено.</div><button class="btn primary wide mt" type="submit">Показать мой профиль</button></form>`);updateGroupSelect32()}
function updateGroupSelect32(){const el=$('#u32-group-select'),level=$('#u32-education')?.value;if(el)el.innerHTML=GROUPS32[level].map(g=>`<option ${g===S.profile.group?'selected':''}>${g}</option>`).join('')}
function clockRefresh32(){const old=U32.lastDay,c=syncClock32();if(document.hidden)return;if((old!==c.iso||U32.lastMinute!==c.minute)&&['home','schedule'].includes(S.page)&&!$('#dialog').open){U32.lastMinute=c.minute;render(false)}}
const render32=render;
render=function(scroll=true){syncGroup32();syncClock32();render32(scroll);if(['templates','create-work'].includes(S.page)){$$('#chrome [data-page="designs"]').forEach(b=>b.classList.add('current'))}if(S.page==='profile'&&!$('#u32-profile-group')){$('#main .page-head')?.insertAdjacentHTML('afterend',button('Учебный профиль и группа','u32-group','id="u32-profile-group"','soft mb'))}};
window.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='reset'){U32.groupKey='';U32.lastDay='';U32.generation=null;U32.receipt=null;U32.used.clear();U32.receipts=[];return}
 if(!['u32-week','u32-today','u32-lesson','u32-group'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();
 if(a==='u32-group')groupDialog32();
 if(a==='u32-week'){S.week=Math.max(-52,Math.min(52,S.week+Number(b.dataset.delta)));render(false)}
 if(a==='u32-today'){S.week=0;S.day=clock32().weekday;render(false)}
 if(a==='u32-lesson'){const v=weekData[Number(b.dataset.day)]?.[Number(b.dataset.event)];if(!v)return;const s=subjects.find(s=>s.id===v[2]);modal('Занятие · демо',`<h2>${s.name}</h2><dl class="mt">${key('Дата',shortDate(b.dataset.date))}${key('Время',v[0]+'–'+v[1])}${key('Аудитория',s.room)}${key('Преподаватель',esc(s.teacher))}</dl>${button('Открыть предмет','subject',`data-id="${s.id}"`,'primary wide mt')}`)}
},true);
window.addEventListener('submit',e=>{if(e.target.id==='u32-group-form'){e.preventDefault();e.stopImmediatePropagation();S.profile.education=$('#u32-education').value;S.profile.group=$('#u32-group-select').value;syncGroup32();closeDialog(true);render(false)}if(e.target.id==='c31-range-form'){e.preventDefault();e.stopImmediatePropagation();const from=$('#c31-from').value,to=$('#c31-to').value,valid=v=>/^\d{4}-\d\d-\d\d$/.test(v)&&!isNaN(Date.parse(v))&&iso32(new Date(v+'T12:00:00Z'))===v;if(!valid(from)||!valid(to)||from>to){$('#c31-date-error').textContent='Укажи корректные даты. Начало не должно быть позже окончания.';return}S.attendanceFrom=from;S.attendanceTo=to;render(false)}},true);
window.addEventListener('change',e=>{if(e.target.id==='u32-education')updateGroupSelect32()});
setInterval(clockRefresh32,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)clockRefresh32()});
// Update at the Samara day boundary, not merely on a page reload.
function scheduleMidnight32(){const n=new Date(),c=clock32(n),wait=(1440-c.minute)*60000-n.getUTCSeconds()*1000-n.getUTCMilliseconds()+40;setTimeout(()=>{clockRefresh32();scheduleMidnight32()},Math.max(50,wait))}
scheduleMidnight32();
