/* Five creation paths share one work/version/confirmation flow. All data stays in memory. */
const KINDS32={pdf:{name:'PDF',format:'pdf',icon:'file',color:'red',description:'Отчёт, конспект или памятка. Точная вёрстка и готовые страницы.'},docx:{name:'Word',format:'docx',icon:'book',color:'blue',description:'Реферат, доклад или письменная работа. Редактируемая структура.'},pptx:{name:'Презентация',format:'pptx',icon:'palette',color:'amber',description:'Понятный сюжет, слайды и выбранное оформление.'},xlsx:{name:'Excel',format:'xlsx',icon:'chart',color:'green',description:'Таблицы, формулы и диаграммы для расчётов.'},gamma:{name:'Продвинутая презентация',format:'pptx',icon:'spark',color:'violet',description:'Отдельный сценарий Gamma API. Дизайнерская подача и выбор шаблона.',price:50}};
Object.assign(LABELS,{designs:'Создать работу',templates:'Выбрать шаблон','create-work':'Задание для работы'});PAID.add('create-work');
function studioKind32(){return KINDS32[U32.studio.kind]||KINDS32.pdf}
function sample32(design,kind=U32.studio.kind){const [id,n,desc,bg,ink,accent]=design;const label=KINDS32[kind]?.name||'PDF';return `<div class="u32-template-art ${kind}" style="--sample-bg:${bg};--sample-ink:${ink};--sample-accent:${accent}" aria-hidden="true"><span>${label}</span><strong>${kind==='xlsx'?'Понятные<br>расчёты.':kind==='pptx'||kind==='gamma'?'Идея.<br>В каждом слайде.':'Содержание.<br>И форма.'}</strong><div class="u32-paper-lines"><i></i><i></i><i></i></div>${kind==='xlsx'?'<div class="u32-mini-bars"><b></b><b></b><b></b><b></b></div>':'<div class="u32-sample-orbit"></div>'}</div>`}
renderers.designs=function(){return head('Создать работу','Выбери формат, затем шаблон — и расскажи, что нужно сделать.',go('Мои готовые работы','works'))+`<div class="u32-format-grid stagger">${Object.entries(KINDS32).map(([id,k])=>`<button class="u32-format-card ${id==='gamma'?'gamma':''}" data-action="u32-kind" data-kind="${id}"><div class="row between"><span class="u32-format-icon ${k.color}">${icon(k.icon)}</span>${k.price?badge('50 ₽ / штука','violet'):badge(k.format.toUpperCase(),k.color)}</div><div class="u32-format-stack" aria-hidden="true"><i></i><i></i><b>${id==='gamma'?'GAMMA':k.format.toUpperCase()}</b></div><h2>${k.name}</h2><p>${k.description}</p><span class="u32-format-cta">Выбрать шаблон ${icon('arrow')}</span></button>`).join('')}</div><div class="note mt"><b>Сейчас это демонстрация</b><p class="small mt-sm">Шаблоны — визуальные образцы. Настоящие PDF, DOCX, XLSX и PPTX не создаются. Gamma API и оплата не подключены. 50 ₽ — заданная цена будущей продвинутой презентации, не списание в демо.</p></div>`};
renderers.templates=function(){const k=studioKind32();return head('Шаблоны · '+k.name,'Выбери оформление. Требования преподавателя всегда важнее декора.',go('Все форматы','designs'))+`<div class="u32-steps"><b>1. Формат</b><b class="active">2. Шаблон</b><span>3. Задание</span></div>${k.price?'<div class="note violet mt mb"><b>Gamma · 50 ₽ за одну презентацию</b><p class="small mt-sm">Это макеты будущего каталога. Реальные темы Gamma нужно получить через API. В демо деньги не списываются.</p></div>':''}<div class="grid g3 stagger mt">${designs.map(d=>`<article class="card u32-template">${sample32(d)}<h3>${d[1]}</h3><p class="small mt-sm">${d[2]}</p>${button('Использовать шаблон','u32-template',`data-template="${d[0]}"`,'soft wide mt')}</article>`).join('')}</div>`};
renderers['create-work']=function(){const k=studioKind32(),v=U32.studio,d=designs.find(d=>d[0]===v.design)||designs[0];return head(k.name+' · '+d[1],'Проверь предмет и требования, прежде чем запускать работу.',go('Другой шаблон','templates'))+`<div class="u32-steps"><b>1. Формат</b><b>2. Шаблон</b><b class="active">3. Задание</b></div><div class="detail-grid mt"><article class="card"><form id="u32-create-form"><label class="field"><span>Тема или название</span><input id="u32-work-title" maxlength="140" required value="${esc(v.title)}" placeholder="Например, эластичность спроса"></label><label class="field"><span>Предмет</span><select id="u32-work-subject">${subjects.map(s=>`<option value="${s.id}" ${s.id===v.subject?'selected':''}>${s.name}</option>`).join('')}</select></label><label class="field"><span>Задание БРСО · необязательно</span><select id="u32-work-task"></select><small>Привязка нужна, чтобы предложить точное место загрузки. Без неё работу можно создать, но нельзя отправлять наугад.</small></label><label class="field"><span>Что нужно сделать</span><textarea id="u32-work-brief" maxlength="2000" rows="4" placeholder="Объём, план, исходные данные, требования преподавателя…">${esc(v.brief||'')}</textarea></label><div id="u32-recipient-hint" class="note"></div><div class="u32-cost"><span>${k.price?'Одна продвинутая презентация':'В рамках AI-пакета'}</span><b>${k.price?'50 ₽':'Лимиты уточняются'}</b></div><button type="submit" class="btn primary wide mt" ${U32.generation?'disabled':''}>Создать демо-карточку ${icon('arrow')}</button><p class="tiny mt-sm">Ничего не оплачивается. Будет создана карточка-пример без настоящего файла.</p></form></article><aside class="stack"><article class="card u32-template">${sample32(d)}<h3>${d[1]}</h3><p class="small mt-sm">${k.format.toUpperCase()}${k.price?' · через Gamma в будущем':''}</p></article><article class="note"><b>Один понятный процесс</b><p class="small mt-sm">Выбор оформления → подготовка → проверка → готовая работа → проверка адресата → отдельное подтверждение загрузки.</p></article></aside></div>`};
function studioFields32(){if(!$('#u32-work-task'))return;const v=U32.studio;$('#u32-work-task').innerHTML='<option value="">Без привязки к заданию</option>'+tasks.filter(t=>t.subject===v.subject).map(t=>`<option value="${t.id}" ${t.id===v.task?'selected':''}>${esc(t.title)}</option>`).join('');const t=teachersFor32(v.subject)[0];$('#u32-recipient-hint').innerHTML=t?`Преподаватель по предмету и группе: <b>${esc(t.name)}</b>. Перед загрузкой потребуется подтверждение.`:'Сначала укажи группу в профиле. Без неё преподавателя не подбираем.'}
function createStudio32(){if(!paid()||U32.generation)return;const v=U32.studio,k=studioKind32(),title=$('#u32-work-title').value.trim();if(!title)return;v.title=title;v.brief=$('#u32-work-brief').value;v.subject=$('#u32-work-subject').value;v.task=$('#u32-work-task').value;const token={},snapshot={...v,title,ownerGroup:groupKey32()};U32.generation=token;modal('Готовим демо-карточку',`<span class="spark-icon">${icon('spark')}</span><h2 class="mt">Формат. Содержание. Проверка.</h2><p class="small mt">Демонстрация интерфейса — не вызов AI или Gamma.</p><div class="preparation-list"><div class="list-row">${icon('check')}Формат и шаблон выбраны</div><div class="list-row">${icon('file')}Сохраняем описание в памяти</div><div class="list-row">${icon('shield')}Настоящий файл не создаётся</div></div>`);setTimeout(()=>{if(U32.generation!==token)return;const w={id:'studio-'+Date.now()+'-'+works.length,task:snapshot.task||null,subject:snapshot.subject,kind:snapshot.kind,format:k.format,design:snapshot.design,title:snapshot.title,brief:snapshot.brief,ownerGroup:snapshot.ownerGroup,version:1,date:shortDate(clock32().iso),studio:true,history:['Создана демо-карточка · '+k.name]};works.unshift(w);S.work=w.id;U32.generation=null;route('work');toast('Карточка готова. Это превью, не настоящий файл.')},800)}
function workSubject32(w){return w.subject||tasks.find(t=>t.id===w.task)?.subject||null}
function target32(w){const sid=workSubject32(w),s=subjects.find(s=>s.id===sid),t=tasks.find(t=>t.id===w.task),ts=teachersFor32(sid);let error='';if(!paid())error='Для новой загрузки нужна активная подписка.';else if(!teaching32())error='Группа не определена. Сначала проверь профиль.';else if(w.ownerGroup!==groupKey32())error='Работа создана для другого учебного профиля. Повторно сверь предмет, задание и адресата.';else if(!s)error='Не определён предмет работы.';else if(!t)error='Выбери точное задание по этому предмету.';else if(t.subject!==sid)error='Предмет работы не совпадает с заданием.';else if(ts.length!==1)error='Адресат неоднозначен. Нельзя выбрать преподавателя автоматически.';else if(S.freshness==='auth_required')error='Нужен повторный вход БРСО.';return {s,t,teacher:ts[0],error}}
function uploadKey32(w){const r=target32(w);return JSON.stringify([w.id,w.version,w.title,w.format,workSubject32(w),w.task,w.ownerGroup,groupKey32(),r.teacher?.id])}
function openUpload32(id){if(!works.some(w=>w.id===id))return;S.work=id;S.uploadValid=true;S.uploadConfirmed=false;U32.receipt={key:uploadKey32(work()),expires:Date.now()+5*60*1000,used:false};route('confirm')}
renderers.works=function(){const list=works.filter(w=>S.filter==='all'||w.format===S.filter);return head('Сделанные задания','Готовые работы и версии. Новое создание — в отдельном каталоге.',go(icon('files')+'Создать работу','designs','primary'))+(S.access==='expired'?'<div class="note amber mb">Срок подписки истёк. Прежние карточки доступны; новая генерация и загрузка закрыты.</div>':'')+`<div class="tabs">${['all','pdf','docx','pptx','xlsx'].map(f=>button(f==='all'?'Все работы':f.toUpperCase(),'work-filter',`data-filter="${f}"`,S.filter===f?'active':'')).join('')}</div><div class="grid g3 stagger">${list.map(w=>`<article class="card work-card"><button class="work-art" data-action="work" data-id="${w.id}" aria-label="Открыть ${esc(w.title)}">${art(w.format)}</button><div class="row between mt-sm">${badge(w.kind==='gamma'?'Gamma · PPTX':w.format.toUpperCase(),w.kind==='gamma'?'violet':'blue')}<span class="tiny">Версия ${w.version}</span></div><h3 class="mt-sm">${esc(w.title)}</h3><p class="small mt-sm">${esc(w.date)} · демо</p><div class="row mt">${button('Открыть','work',`data-id="${w.id}"`,'soft grow')}${button(icon('download'),'download',`data-id="${w.id}" aria-label="Скачать описание макета"`,'sm')}</div></article>`).join('')||'<article class="card"><h3>Работ этого формата пока нет</h3></article>'}</div>`};
renderers.work=function(){const w=work(),sid=workSubject32(w),s=subjects.find(s=>s.id===sid),t=tasks.find(t=>t.id===w.task),d=designs.find(d=>d[0]===w.design)||designs[0];return head(esc(w.title),`Версия ${w.version} · ${w.kind==='gamma'?'Gamma · ':''}${w.format.toUpperCase()} · демо-карточка`,go('Все работы','works'))+`<div class="detail-grid"><section class="stack"><article class="card u32-template">${sample32(d,w.kind||w.format)}<h3>Описание работы</h3><p class="small mt">${esc(w.brief||t?.description||'Свободная работа без привязки к заданию.')}</p><div class="note mt">Настоящий ${w.format.toUpperCase()} не создавался. Можно посмотреть сценарий загрузки и скачать TXT с описанием макета.</div><div class="row wrap mt">${button(icon('download')+'Скачать описание','download',`data-id="${w.id}"`,'soft')}${button(icon('refresh')+'Переделать','revision',`data-id="${w.id}"`)}</div></article><article class="card"><h3>Версии</h3>${w.history.map((v,i)=>`<div class="list-row"><b>v${i+1}</b><span>${esc(v)}</span></div>`).join('')}</article></section><aside class="stack"><article class="card"><h3>Куда загрузить</h3><dl class="mt">${key('Предмет',esc(s?.name||'Не указан'))}${key('Группа',esc((w.ownerGroup||'').split(':')[1]||'Не указана'))}${key('Задание',esc(t?.title||'Нужно выбрать перед загрузкой'))}</dl><p class="small mt">Преподаватель определяется по предмету и группе. Загрузка начнётся только после отдельной проверки точного адресата и файла.</p>${button(icon('upload')+'Загрузить в БРСО','u32-upload',`data-id="${w.id}"`,'primary wide mt')}</article>${go('Создать ещё одну работу','designs','wide')}</aside></div>`};
renderers.confirm=function(){const w=work(),r=target32(w),receipt=U32.receipt,key32=uploadKey32(w),used=U32.used.has(key32),invalid=!receipt||receipt.key!==key32||Date.now()>receipt.expires||!S.uploadValid;const blocked=r.error||(used?'Эта версия уже подтверждена в демо. Повторная отправка отключена.':invalid?'Предпросмотр истёк или файл изменился. Открой новый.':'');return head('Проверить и загрузить','Адресат подобран по предмету и группе. Последнее подтверждение — за тобой.')+`<div class="detail-grid"><article class="card"><div class="row between"><span class="spark-icon">${icon('shield')}</span>${badge('Никакой реальной отправки','blue')}</div><h2 class="mt">${r.teacher?'Адресат найден':'Нужно уточнение'}</h2><dl class="mt">${key('Группа',esc(S.profile.group||'Не указана'))}${key('Предмет',esc(r.s?.name||'Не определён'))}${key('Преподаватель',esc(r.teacher?.name||'Не определён'))}${key('Задание',esc(r.t?.title||'Не выбрано'))}${key('Файл',esc(w.title)+'.'+w.format)}${key('Версия','v'+w.version)}</dl>${!r.t&&r.s?`<label class="field"><span>Выбери точное задание</span><select id="u32-upload-task"><option value="">Не выбрано</option>${tasks.filter(t=>t.subject===r.s.id).map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select></label>`:''}<div class="note ${blocked?'amber':'blue'} mt" id="u32-confirm-status">${blocked||'Проверь данные. В рабочем продукте здесь подтверждается один точный файл; загрузка не равна оценке преподавателя.'}</div><label class="check-row"><input id="u32-upload-check" type="checkbox" ${blocked?'disabled':''}>Проверил предмет, преподавателя, задание и эту версию файла.</label>${button(used?'Уже подтверждено в демо':'Подтвердить демо-загрузку','u32-confirm','id="u32-confirm-btn" disabled','primary wide')}<p class="tiny mt-sm">Здесь не загружается файл и не создаётся настоящая запись БРСО.</p></article><aside class="stack"><article class="card"><h3>Контроль перед отправкой</h3><p class="small mt-sm">При смене файла, группы или истечении сессии подтверждение отменяется. Скрытых повторов нет.</p>${button('Имитировать смену файла','u32-invalidate','','wide mt')}${button('Имитировать истечение сессии','u32-expire','','wide mt-sm')}${button('Новый предпросмотр','u32-upload',`data-id="${w.id}"`,'soft wide mt-sm')}</article>${go('Вернуться к работе','work','wide')}</aside></div>`};
const uploads32=renderers.uploads;
renderers.uploads=()=>head('Загруженные задания','Демонстрационный журнал. Реальные файлы не отправлялись.')+`<div class="note mb mt">«Подтверждено» в этом макете — только проверка интерфейса. Это не подтверждение загрузки или принятия преподавателем.</div><div class="grid g2">${U32.receipts.map(r=>`<article class="card">${badge('Подтверждено только в демо','amber')}<h3 class="mt">${esc(r.title)}</h3><dl class="mt">${key('Преподаватель',esc(r.teacher))}${key('Предмет',esc(r.subject))}${key('Версия','v'+r.version)}${key('Реальная загрузка','Не выполнялась')}</dl></article>`).join('')||'<article class="card"><h3>В текущем просмотре подтверждений нет</h3><p class="small mt-sm">Создай демо-карточку, проверь адресата и пройди подтверждение.</p></article>'}</div>${go('К моим работам','works','soft mt')}`;
const space32=renderers.space,study32=renderers.study;
renderers.space=()=>space32().replaceAll('Оформление файлов','Создать работу').replace('Стиль PDF, Word, Excel и презентаций.','Пять форматов и выбор шаблонов.').replace('Частные отзывы и сведения о преподавателях.','Оценки, краткие характеристики и предметы твоей группы.');
renderers.study=()=>study32().replace('Предметы и частные отзывы.','Оценки, характеристики и предметы твоей группы.')+`<div class="u32-create-callout">${icon('files')}<div><h3>Нужен готовый документ?</h3><p class="small">PDF, Word, Excel, презентация или Gamma.</p></div>${go('Создать работу','designs','soft')}</div>`;
const renderStudio32=render;
render=function(scroll=true){renderStudio32(scroll);if(S.page==='create-work'&&paid())studioFields32()};
window.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;if(a==='save-revision'){U32.receipt=null;return}if(!['u32-kind','u32-template','u32-upload','open-confirm','u32-confirm','confirm-upload','u32-invalidate','u32-expire','renew-upload'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();
 if(a==='u32-kind'&&KINDS32[b.dataset.kind]){U32.studio.kind=b.dataset.kind;route('templates')}
 if(a==='u32-template'&&designs.some(d=>d[0]===b.dataset.template)){U32.studio.design=b.dataset.template;route('create-work')}
 if(['u32-upload','open-confirm','renew-upload'].includes(a))openUpload32(id||S.work);
 if(['u32-confirm','confirm-upload'].includes(a)){const w=work(),r=target32(w),key32=uploadKey32(w),receipt=U32.receipt;if(r.error||!$('#u32-upload-check')?.checked||!S.uploadValid||!receipt||receipt.key!==key32||receipt.used||Date.now()>receipt.expires||U32.used.has(key32)){toast('Подтверждение недействительно. Нужен новый просмотр.');return}receipt.used=true;U32.used.add(key32);U32.receipts.push({title:w.title,version:w.version,subject:r.s.name,teacher:r.teacher.name});S.uploadConfirmed=true;render(false);toast('Подтверждено только в демо. Файл не отправлен.')}
 if(a==='u32-invalidate'){work().version++;work().history.push('Демо-смена файла перед загрузкой');S.uploadValid=false;render(false)}
 if(a==='u32-expire'){S.freshness='auth_required';S.uploadValid=false;U32.receipt=null;render(false)}
},true);
window.addEventListener('input',e=>{if(e.target.id==='u32-work-title')U32.studio.title=e.target.value;if(e.target.id==='u32-work-brief')U32.studio.brief=e.target.value});
window.addEventListener('change',e=>{const id=e.target.id;if(id==='u32-work-subject'){U32.studio.subject=e.target.value;U32.studio.task='';studioFields32()}if(id==='u32-work-task')U32.studio.task=e.target.value;if(id==='u32-upload-task'){const t=tasks.find(t=>t.id===e.target.value);if(t&&t.subject===workSubject32(work())){work().task=t.id;openUpload32(S.work)}}if(id==='u32-upload-check'){const b=$('#u32-confirm-btn');if(b)b.disabled=!e.target.checked}},true);
window.addEventListener('submit',e=>{if(e.target.id==='u32-create-form'){e.preventDefault();e.stopImmediatePropagation();createStudio32()}},true);

// Preserve version confirmation semantics while escaping editable work titles.
window.addEventListener('click',e=>{const b=e.target.closest('[data-action="revision"]');if(!b||b.disabled)return;e.preventDefault();e.stopImmediatePropagation();if(!works.some(w=>w.id===b.dataset.id))return;S.work=b.dataset.id;if(!paid()){modal('Переделка доступна с подпиской',`<p class="small">Прежняя работа остаётся доступной.</p>${go('Посмотреть тарифы','billing','primary wide mt')}`);return}modal('Что улучшить?',`<p class="small">${esc(work().title)} · версия ${work().version}</p><label class="field"><span>Пожелания к новой версии</span><textarea id="revision-text" maxlength="800" placeholder="Что поменять в следующей версии?"></textarea></label><div class="note mt">Создаётся только запись версии в макете. Настоящий файл не изменяется.</div>${button('Добавить демо-версию','save-revision','','primary wide mt')}`,'revision')},true);
