/* UI capability selectors, not provider/model configuration or a trained corpus claim. */
const MODELS32={mentor:{name:'Наставник',caption:'быстро'},master:{name:'Мастер',caption:'глубокий разбор'}};
function tutorOptions32(t=tutorState()){t.model??='mentor';t.source??='lectures';t.urls??=[];return t}
const tutorNew32=tutorNew;
tutorNew=function(sid=S.subject){const old=tutorOptions32(),next=tutorNew32(sid);Object.assign(next,{model:old.model,source:old.source,urls:[...old.urls]});return next};
const tutorPage32=renderers.tutor;
renderers.tutor=function(){const t=tutorOptions32();let html=tutorPage32();const legend=`<div class="u32-lecture-line">${icon('book')}<span>По лекциям СГЭУ · СПО и университет</span><span class="u32-demo-tag">База лекций не подключена в демо</span></div>`;
 html=html.replace('<section class="c31-tutor"',legend+'<section class="c31-tutor"');
 const options=`<div class="u32-tutor-settings"><label><span>Твой учитель</span><select id="u32-model" ${t.pending?'disabled':''} aria-label="Модель учителя">${Object.entries(MODELS32).map(([id,m])=>`<option value="${id}" ${id===t.model?'selected':''}>${m.name} · ${m.caption}</option>`).join('')}</select></label><label><span>Основа ответа</span><select id="u32-source" ${t.pending?'disabled':''} aria-label="Источники ответа"><option value="lectures" ${t.source==='lectures'?'selected':''}>По лекциям</option><option value="web" ${t.source==='web'?'selected':''}>Из интернета</option></select></label>${t.source==='web'?button(icon('link')+(t.urls.length?'Источники: '+t.urls.length:'Указать источники'),'u32-sources','','sm'):''}</div>`;
 html=html.replace('<div class="c31-transcript"',options+'<div class="c31-transcript"');
 html=html.replace('</div><button class="c31-example"',`<button class="u32-studio-shortcut" data-action="route" data-page="designs"><span class="c31-prompt-icon">${icon('files')}</span><span><b>Создать работу</b><small>PDF · Word · Excel · презентации</small></span>${icon('up')}</button></div><button class="c31-example"`);
 return html;
};
const tutorMessage32=tutorMessage;
tutorMessage=function(m,i){let html=tutorMessage32(m,i);if(m.options){const o=m.options;html=html.replace('<div class="c31-message-body">',`<div class="u32-message-context">${esc(MODELS32[o.model]?.name||'Наставник')} · ${o.source==='web'?'Источники из интернета':'По лекциям'}${o.urls?.length?' · '+o.urls.length+' ссылок':''}</div><div class="c31-message-body">`)}return html};
tutorSend=function(){const t=tutorOptions32();if(!paid()||t.pending)return;const text=t.draft.trim();if(!text&&!t.files.length)return;const options={model:t.model,source:t.source,urls:[...t.urls],mode:t.mode};t.messages.push({role:'user',text,files:t.files.map(f=>({...f})),options});if(t.title==='Новый диалог')t.title=(text||t.files[0].name).slice(0,42);t.draft='';t.files=[];t.pending=true;S.chat=t.messages;render(false);t.timer=setTimeout(()=>{if(!t.pending)return;t.pending=false;const s=subjects.find(s=>s.id===t.subject);let reply=options.mode==='prepare'?'План подготовки к сессии':'Разберём по шагам';reply+='\n\nПредмет: '+(s?.name||'все предметы')+'.';reply+='\n\n'+(options.source==='lectures'?'Основа: лекции СГЭУ. В демо они не подключены, поэтому ниже только пример структуры, а не ответ по лекциям.':options.urls.length?'Выбраны источники:\n'+options.urls.join('\n')+'\nВ демо страницы не открываются и их содержание не проверяется.':'Выбран интернет-поиск. В демо поиск не запускается; источники не выдумываются.');reply+='\n\n1. Собрать подтверждённые вопросы и требования преподавателя.\n\n2. Разделить темы на понятные блоки и повторить определения с примерами.\n\n3. Разобрать типовые задания и проверить понимание.';if(options.model==='master')reply+='\n\n4. Сопоставить методы, разобрать исключения и составить вопросы повышенной сложности.';reply+='\n\nЭто заранее подготовленный пример интерфейса. Реальная модель не вызвана; сообщение и источники никуда не отправлялись.';t.messages.push({role:'assistant',text:reply,options});if(S.page==='tutor'&&S.tutorActive===t.id)render(false)},650)};
function sourcesDialog32(){const t=tutorOptions32();modal('Источники для ответа',`<p class="small">Добавь до пяти ссылок — по одной на строку. В продукте учитель будет использовать выбранные страницы и показывать ссылки на использованные материалы.</p><form id="u32-sources-form"><label class="field"><span>Адреса страниц</span><textarea id="u32-source-urls" rows="5" maxlength="2500" placeholder="https://…">${esc(t.urls.join('\n'))}</textarea></label><p id="u32-source-error" role="alert"></p><div class="note">Здесь ссылки только сохраняются в текущем диалоге. Содержимое сайтов не загружается.</div><button class="btn primary wide mt" type="submit">Использовать эти источники</button></form>`)}
renderers.exams=function(){return head('Сессия и зачёты','Выбери предмет — учитель сразу получит запрос на подготовку.',button(icon('spark')+'Подготовиться ко всей сессии','u32-exam','data-id="all"','soft'))+fresh()+`<div class="grid g2 mt stagger">${subjects.map(s=>`<article class="card exam-card"><div class="row"><span class="date-block"><b>${s.exam.split(' ')[0]}</b><small>ЯНВ · ДЕМО</small></span><div class="grow"><h3>${s.name}</h3><p class="small mt-sm">${esc(s.teacher)}</p></div></div><p class="tiny mt-sm">Дата — пример, не подтверждённый срок БРСО.</p><div class="preparation-list">${['Посмотреть требования','Повторить основные темы','Проверить себя'].map((v,j)=>`<label class="check-row"><input type="checkbox" data-prep="${s.id}-${j}" ${S.prep.has(s.id+'-'+j)?'checked':''}>${v}</label>`).join('')}</div>${button(icon('spark')+'Подготовиться к сессии','u32-exam',`data-id="${s.id}"`,'primary wide')}<p class="tiny mt-sm">Откроется чат с готовым сообщением по этому предмету.</p></article>`).join('')}</div>`};
function examChat32(id){if(!paid()){route('billing');return}const s=subjects.find(s=>s.id===id)||sub(),t=tutorNew(s.id);t.mode='prepare';t.draft=id==='all'?'Подготовь меня к сессии по предметам: '+subjects.map(x=>x.name).join(', ')+'. Составь план по темам, выдели сложные вопросы и проведи самопроверку. Требования и даты нужно подтвердить по материалам.':'Подготовь меня к сессии по предмету «'+s.name+'». Преподаватель: '+s.teacher+'. В демо дата: '+s.exam+' (не подтверждена БРСО). Составь план подготовки, объясни основные темы и задай вопросы для самопроверки.';route('tutor');tutorSend()}
window.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(!['u32-exam','prepare','u32-sources'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();if(a==='u32-sources')sourcesDialog32();else{b.disabled=true;examChat32(b.dataset.id||S.subject)}},true);
window.addEventListener('change',e=>{if(e.target.id==='u32-model'){const t=tutorOptions32();if(!t.pending&&MODELS32[e.target.value])t.model=e.target.value;render(false)}if(e.target.id==='u32-source'){const t=tutorOptions32();if(!t.pending&&['lectures','web'].includes(e.target.value))t.source=e.target.value;render(false)}},true);
window.addEventListener('submit',e=>{if(e.target.id!=='u32-sources-form')return;e.preventDefault();e.stopImmediatePropagation();const lines=$('#u32-source-urls').value.split(/\n/).map(v=>v.trim()).filter(Boolean);if(lines.length>5){$('#u32-source-error').textContent='Можно выбрать не больше пяти ссылок.';return}const urls=[];for(const v of lines){try{const u=new URL(v);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||!u.hostname.includes('.'))throw Error();urls.push(u.href)}catch{$('#u32-source-error').textContent='Нужны полные http/https ссылки без логина и пароля.';return}}const t=tutorOptions32();t.urls=[...new Set(urls)];t.source='web';closeDialog(true);render(false)},true);
